### ISSUE TITLE
Manual?

### ISSUE THREAD

**Issue by cmountvpr** [AmalgamatedHarmonics/Prism#1]
This one looks REAL interesting. Sure would appreciate a manual! :)

**Comment by jhoar** [comment]
I recommend starting with the original manual 

http://4mscompany.com/SMR/manual/SMR-manual-1.1.1.pdf

The manual will go here:

https://github.com/AmalgamatedHarmonics/Prism/wiki/Rainbow

But for the time being it's more a collection of notes about where Rainbow is deviating substantially from the original hardware.

**Comment by jhoar** [comment]
Manual here:

https://github.com/AmalgamatedHarmonics/Prism/blob/master/doc/PrismUM.pdf
