### ISSUE TITLE
Rack crashing in a seemingly random way when using Prism

### ISSUE THREAD

**Issue by spectromas** [AmalgamatedHarmonics/Prism#16]
I'm not what information to provide here because I don't know how to reproduce it but when using Prism on linux, Rack is crashing at apparently random points. I think the crashes are not related to any particular steps, as far as I can tell, but after a while (whether adjusting Prism or adjusting something else entirely in the patch) Rack crashes. 

The log says the following: 

```
[942.584 fatal src/main.cpp:39] Fatal signal 11. Stack trace:
9: /home/alex/.local/opt/Rack/Rack() [0x56b981]
8: /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7fbcdd59cf20]
7: /home/alex/.local/opt/Rack/Rack(speex_resampler_destroy+0x4) [0x81944d]
6: /home/alex/.Rack/plugins-v1/Prism/plugin.so(_ZN7rainbow5Audio15ChannelProcess6ERNS_10ControllerERN4rack6engine5InputERNS4_6OutputE+0x33d) [0x7fbcb7dd856b]
5: /home/alex/.Rack/plugins-v1/Prism/plugin.so(_ZN7Rainbow7processERKN4rack6engine6Module11ProcessArgsE+0x1afe) [0x7fbcb7ddd86e]
4: /home/alex/.local/opt/Rack/Rack() [0x5b3eb3]
3: /home/alex/.local/opt/Rack/Rack(_ZN4rack6engine12EngineWorker3runEv+0x15e) [0x5b5310]
2: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbd9e0) [0x7fbcddfc29e0]
1: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7fbcdfb6d6db]
0: /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fbcdd67f88f]
```

I am using Rack with Jack running at 44.1khz, 1024, 3. Seems like there is an issue with the cpu mode running at 48k when the Rack sample rate is not 48k?

**Comment by jhoar** [comment]
Hi,

Is it misbehaving in 96Khz mode?

**Comment by spectromas** [comment]
Annoyingly, I can't reproduce this now so I suppose this should be closed. 
I think I did try 96Khz mode and the stability improved but I can't say for sure now.
