### ISSUE TITLE
Poly 12 Env Out ?

### ISSUE THREAD

**Issue by Petervos2018** [AmalgamatedHarmonics/Prism#8]
Should this not be 6 Out ?

![rainb12env_cr](https://user-images.githubusercontent.com/46076474/64495406-f42e1200-d299-11e9-8aac-ee0325e81f65.jpg)

Boy does it look gorgeous (and still green ;)

Greetings Peter.

**Comment by jhoar** [comment]
Channels 7-12 have the final calculated level.

**Comment by Petervos2018** [comment]
As it says in the manual, sorry I didn't read that.

Thanks Peter
